<?php

namespace UnicornFarmBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UnicornFarmBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @param int $postId
     * @return Post
     */
    public function findById($postId)
    {
        $qb = $this->createQueryBuilder('p');

        $qb->select('p')
            ->where('p.id = :mid')
            ->setParameter('mid', $postId);

        $query = $qb->getQuery();

        return $query->getSingleResult();
    }

    /**
     * @param int $unicornId
     * @return Post
     */
    public function findAllByUnicornId($unicornId)
    {
        $qb = $this->createQueryBuilder('p');

        $qb->select('p')
            ->where('p.unicorn = :mid')
            ->setParameter('mid', $unicornId);

        $query = $qb->getQuery();

        return $query->getResult();
    }

    /**
     * @param int $userId
     * @return Post
     */
    public function findAllByUserId($userId)
    {
        $qb = $this->createQueryBuilder('p');

        $qb->select('p')
            ->where('p.user = :mid')
            ->setParameter('mid', $userId);

        $query = $qb->getQuery();

        return $query->getResult();
    }

    /**
     * @param Post $post
     */
    public function save(Post $post)
    {
        $this->getEntityManager()->persist($post);
        $this->getEntityManager()->flush();
    }

    /**
     * @param Post $post
     */
    public function delete(Post $post)
    {
        $this->getEntityManager()->remove($post);
        $this->getEntityManager()->flush();
    }
}
