<?php

namespace UnicornFarmBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UnicornFarmBundle\Entity\Unicorn;

/**
 * UnicornRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnicornRepository extends EntityRepository implements UnicornRepositoryInterface
{
    /**
     * @param int $unicornId
     * @return Unicorn
     */
    public function findById($unicornId)
    {
        $qb = $this->createQueryBuilder('u');

        $qb->select('u')
            ->where('u.id = :mid')
            ->setParameter('mid', $unicornId);

        $query = $qb->getQuery();

        return $query->getSingleResult();
    }

    /**
     * @param Unicorn $unicorn
     */
    public function save(Unicorn $unicorn)
    {

    }

    /**
     * @param Unicorn $unicorn
     */
    public function delete(Unicorn $unicorn)
    {

    }
}
