<?php

namespace UnicornFarmBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UnicornFarmBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param string $firstName
     * @param string $lastName
     * @return Unicorn
     */
    public function findByUserName($firstName, $lastName)
    {
        $qb = $this->createQueryBuilder('u');

        $qb->select('u')
            ->where('u.firstName = :ufn')
            ->setParameter('ufn', $firstName)
            ->andWhere('u.lastName = :uln')
            ->setParameter('uln', $lastName);

        $query = $qb->getQuery();

        return $query->getOneOrNullResult();
    }

    /**
     * @param User $user
     */
    public function save(User $user)
    {
        $this->getEntityManager()->persist($user);
        $this->getEntityManager()->flush();
    }

    /**
     * @param User $user
     */
    public function delete(User $user)
    {
        $this->getEntityManager()->remove($user);
        $this->getEntityManager()->flush();
    }
}
